Add filterCFPs.js script
scraly/developers-conferences-agenda pull request #1001
Opened 2024-05-06 16:53 UTC by thierrylee

2024-05-18 10:22 UTC, scraly commented
Hi
thanks for the PR
I think this kind of script can help other people :) 

Do you know if it's possible to add the "France" country parameter in a variable of the function?

2024-05-18 10:22 UTC, scraly requested changes
just a typo to fix

2024-05-18 10:22 UTC, scraly commented on scripts/README.md
> +Imports the JSOn file of all the events into a Google Spreadsheet table.
```suggestion
Imports the JSON file of all the events into a Google Spreadsheet table.
```

2024-05-21 07:03 UTC, thierrylee commented
> Hi thanks for the PR I think this kind of script can help other people :)
> 
> Do you know if it's possible to add the "France" country parameter in a variable of the function?

Sure, of course !
Though I'll need to create a "main" function without parameters. This "main" function will called by Google App Scripts triggers which cannot provide parameters to a method call.

2024-05-27 09:12 UTC, scraly commented
Thanks @thierrylee for the script, I think it can help people :)

2024-05-27 09:12 UTC, scraly approved these changes

2024-05-27 09:12 UTC, merged