Add the regions filter and fix some old data
scraly/developers-conferences-agenda pull request #1111
Opened 2024-08-22 14:17 UTC by jespino

Fixes #1077

2024-08-23 21:30 UTC, scraly commented
Thanks :)
A first remark: the new "validateRegions.js" script is missing in run.sh

2024-08-23 21:32 UTC, scraly commented
I tested it and I saw a bug

If we select a region, all of the countries are still displayed in the list, so we can select a region with a country that is not in this country, example:

<img width="1427" alt="image" src="https://github.com/user-attachments/assets/9e0760ae-994d-4603-aa0c-c1ffa3ba59c0">


A suggestion may be to hide the country list if the region is selected. And if the region is equals to All, then the country list is displayed again?

2024-08-23 21:35 UTC, scraly requested changes

2024-08-23 21:35 UTC, scraly commented on .github/workflows/check_regions.yml
> +  MdValidator:
```suggestion
  RegionsValidator:
```

2024-08-24 09:32 UTC, jespino commented
@scraly I update it to filter the countries and only list the ones that are inside the region, and whenever you change the region I automatically deselect the country.

2024-08-24 11:51 UTC, scraly commented
Thanks
I observed a new issue:
in the first load, when you click in the filter, the country list is hidden, we should see the list:
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/28486644-6189-4144-8ada-19f0a3c95e54">

Users should be allowed to select a country if they want (to display events in Spain for example :) )

2024-08-24 16:09 UTC, jespino commented
@scraly that was an easy one. Fixed.

2024-08-24 16:54 UTC, scraly commented
Thanks ^^
Easy fix and useful :) 

I see another thing, in the list of countries (after selecting a region), is it possible to sort the countries alphabetically?

2024-08-25 19:10 UTC, jespino commented
@scraly done

2024-08-25 19:49 UTC, scraly requested changes

2024-08-25 19:49 UTC, scraly commented on page/src/misc/regions.json
> +  "South America": ["Argentina", "Brazil", "Chile", "Peru", "Colombia", "Bolivia", "Columbia"]
```suggestion
  "South America": ["Argentina", "Brazil", "Chile", "Peru", "Colombia", "Bolivia"]
```

2024-08-26 08:35 UTC, scraly approved these changes
approved

2024-08-26 08:35 UTC, merged