improved footer
scraly/developers-conferences-agenda pull request #1163
Opened 2024-10-01 12:49 UTC by YadlaMani

2024-10-01 12:50 UTC, YadlaMani commented
Closes #1163 
@scraly

2024-10-08 10:05 UTC, scraly commented
Hi, thanks for the PR

I have a remark:
I tested it and without the underline for a link, people don't know that a word is in fact a link.

2024-10-08 10:40 UTC, YadlaMani commented
Will add the underline

2024-10-08 16:06 UTC, YadlaMani commented
@scraly fixed it added underline again

2024-11-11 04:34 UTC, sudhanshutech requested changes

2024-11-11 04:34 UTC, sudhanshutech commented on package-lock.json
> +{
@YadlaMani I guess there should be no change related to package lock file. Will you revert it.

2024-11-26 21:36 UTC, scraly commented
You're right, the website needs a new and improved footer.

2024-12-31 11:37 UTC, closed without merging