Adding more events
scraly/developers-conferences-agenda pull request #1196
Opened 2024-11-06 09:36 UTC by jespino

2024-11-06 10:18 UTC, scraly requested changes
Thanks @jespino 
just few remarks :)

2024-11-06 10:18 UTC, scraly commented on README.md
> +* 26: [The DEVOPS Conference London 2025](https://www.thedevopsconference.com/) - London (UK) <a href="https://sessionize.com/the-devops-conference-london-2025"><img alt="CFP The DEVOPS Conference Lo
```suggestion
* 26: [The DEVOPS Conference London 2025](https://www.thedevopsconference.com/london) - London (UK) <a href="https://sessionize.com/the-devops-conference-london-2025"><img alt="CFP The DEVOPS Conference London 2025" src="https://img.shields.io/static/v1?label=CFP&message=until%2022-November-2024&color=green"></a>
```

2024-11-06 10:18 UTC, scraly commented on README.md
> +* 9: [Weblica 2025](https://weblica.hr/) - Štrigova (Croatia) <a href="https://sessionize.com/weblica-2025"><img alt="CFP Weblica 2025" src="https://img.shields.io/static/v1?label=CFP&message=until%2
```suggestion
* 9: [Weblica 2025](https://weblica.hr/) - Strigova (Croatia) <a href="https://sessionize.com/weblica-2025"><img alt="CFP Weblica 2025" src="https://img.shields.io/static/v1?label=CFP&message=until%2016-February-2025&color=green"></a>
```

2024-11-06 10:18 UTC, scraly commented on page/src/misc/geolocations.json
> +  "trigova (Croatia)": {
```suggestion
  "Strigova (Croatia)": {
```

2024-11-07 10:01 UTC, jespino commented
@scraly fixed, thanks!

2024-11-08 10:49 UTC, merged

2024-11-08 10:49 UTC, scraly commented
thanks :)