Add VIVA Tech
scraly/developers-conferences-agenda pull request #186
Opened 2022-05-23 20:26 UTC by Ardemius

2022-05-23 20:27 UTC, scraly requested changes

2022-05-23 20:27 UTC, scraly commented on README.md
> +* 15-18: [VIVA Technology](https://vivatechnology.com/) - Paris
```suggestion
* 15-18: [VIVA Technology](https://vivatechnology.com/) - Paris (France)
```

2022-05-23 20:47 UTC, Ardemius reviewed
Oups, sorry for the miss ^^'

2022-05-24 05:55 UTC, scraly approved these changes

2022-05-24 05:55 UTC, merged

2022-05-24 05:56 UTC, scraly commented
Thanks :)