Added NODES 2022 conference Nov 16-17
scraly/developers-conferences-agenda pull request #228
Opened 2022-08-11 15:36 UTC by jexp

thank you 🙏

2022-08-13 18:45 UTC, scraly requested changes

2022-08-13 18:45 UTC, scraly commented on README.md
> +* 16-17: [NODES 2022 (Neo4j Online Developer Expo and Summit)](https://neo4j.com/nodes-2022/) - Online <a href="[https://sessionize.com/agile-tour-toulouse-2022/](https://sessionize.com/neo4j-nodes-2
```suggestion
* 16-17: [NODES 2022 (Neo4j Online Developer Expo and Summit)](https://neo4j.com/nodes-2022/) - Online <a href="https://sessionize.com/neo4j-nodes-2022/"><img alt="Neo4j Online Developer Expo and Summit)" src="https://img.shields.io/static/v1?label=CFP&message=until%2020-Aug-2022&color=green"> </a>
```

2022-08-18 09:04 UTC, scraly commented
Can you fix the copy/paste typos?
Thanks

2022-08-18 16:06 UTC, jexp commented
I'm really sorry for that, took your commit.

2022-08-18 16:08 UTC, merged