Add Parisjug events
scraly/developers-conferences-agenda pull request #273
Opened 2022-11-28 17:59 UTC by kanedafromparis

2022-12-03 21:50 UTC, scraly commented
Pour javaday et jchateau y a pas de soucis,
par contre pour le paris jug c'est un meetup.

Pour les meetups je pense qu'il serait possible et utile de faire un repo a part (car tous ne sont pas/plus sur la plateforme meetup, tu en penses quoi) ?

2022-12-04 17:55 UTC, kanedafromparis commented
À mon avis, la fragmentation complique les choses, l’avantage de ton repo est de regrouper les évènements, c’est devenu une référence, donc je pense qu’y regrouper les "conferences" et les "meetup" fait sens. 
Cela dit :
 1 - la mise à jour étant plus fréquente, cela demande probablement plus de boulot 
 2 - s’il y a trop d’événements, cela peut rendre le calendrier moins lisible (trop dense)
 > on pourrait les différencier visuellement
 > on pourrait mettre une section différente

2022-12-04 17:56 UTC, kanedafromparis commented
Cela dit, si tu préfères, je retire les soirées ParisJUG.

2022-12-04 18:18 UTC, scraly requested changes

2022-12-04 18:18 UTC, scraly commented on README.md
> +* 6: [monthly-ParisJUG](https://www.parisjug.org/xwiki/wiki/oldversion/view/Meeting/20221206) - Paris (France)
```suggestion
* 6: [Paris JUG Meetup](https://www.parisjug.org/xwiki/wiki/oldversion/view/Meeting/20221206) - Paris (France) <a href="https://www.parisjug.org/xwiki/wiki/oldversion/view/Meeting/20221206"><img alt="Meetup Paris JUG" src="https://img.shields.io/static/v1?label=Meetup&message=19h30&color=blue"> </a>
```

2022-12-04 18:18 UTC, scraly commented on README.md
> +* 6: [Paris JUG Meetup](https://www.parisjug.org/xwiki/wiki/oldversion/view/Meeting/20221206) - Paris (France) <a href="https://www.parisjug.org/xwiki/wiki/oldversion/view/Meeting/20221206"><img alt=
```suggestion
* 6: [Paris JUG Meetup](https://www.parisjug.org/xwiki/wiki/oldversion/view/Meeting/20221206) - Paris (France) <a href="https://www.parisjug.org/xwiki/wiki/oldversion/view/Meeting/20221206"><img alt="Meetup Paris JUG" src="https://img.shields.io/static/v1?label=Meetup&message=19h30&color=blue"> </a>
```

2023-01-29 08:59 UTC, scraly commented
commited - fixed :)

2023-01-29 08:59 UTC, closed without merging