Add DevOps Enterprise Summit
scraly/developers-conferences-agenda pull request #366
Opened 2023-02-28 13:56 UTC by ojacques

Add the DevOps Enterprise Summit, Amsterdam.

2023-03-01 13:37 UTC, scraly requested changes

2023-03-01 13:37 UTC, scraly commented on README.md
> +* 16-17: [DevOps Enterprise Summit Amsterdam](https://itrevolution.com/product/devops-enterprise-summit-amsterdam-2023/) - Amsterdam (Netherlands) <a href="[https://sessionize.com/kafka-summit-london
```suggestion
* 16-17: [DevOps Enterprise Summit Amsterdam](https://itrevolution.com/product/devops-enterprise-summit-amsterdam-2023/) - Amsterdam (Netherlands) <a href="https://sessionize.com/kafka-summit-london-2023/"><img alt="DevOps Enterprise Summit Amsterdam 2023" src="https://img.shields.io/static/v1?label=CFP&message=until%2013-March-2023&color=green"></a>
```

2023-03-02 14:08 UTC, scraly commented
Is the CFP link is correct? 😉

2023-03-03 15:39 UTC, ojacques commented
All fixed!

2023-03-03 17:06 UTC, merged

2023-03-03 17:07 UTC, scraly commented
Thanks 🙂