Add adeo DevSummit 2023
scraly/developers-conferences-agenda pull request #406
Opened 2023-04-04 12:51 UTC by Damien-VS

2023-04-04 14:46 UTC, scraly requested changes

2023-04-04 14:46 UTC, scraly commented on page/src/components/SelectedEvents.js
> +		<h3 className="eventDateDisplay">{(date.getFullYear()}-({('0' + date.getMonth() + 1).slice(-2)}-{('0' + date.getDate()).slice(-2)}</h3>
Is it in another PR? :)

2023-04-04 14:46 UTC, scraly requested changes

2023-04-04 14:46 UTC, scraly commented on README.md
> +* 20-22 [adeo DevSummit](https://forms.gle/YPcjupChvqQif85B9) - Lille (France) <a href="https://forms.gle/YPcjupChvqQif85B9"><img alt="CFP adeo DevSummit 2023" src="https://img.shields.io/static/v1?l
```suggestion
* 20-22: [Adeo DevSummit](https://forms.gle/YPcjupChvqQif85B9) - Lille (France) <a href="https://forms.gle/YPcjupChvqQif85B9"><img alt="CFP adeo DevSummit 2023" src="https://img.shields.io/static/v1?label=CFP&message=until%2019-May-2023&color=green"></a>
```

2023-04-14 17:22 UTC, scraly commented
Il y a t'il une page qui explique ce qu'est le adeo dev summit ? (car les deux liens menent au cfp)
merci :)

2023-04-17 07:05 UTC, Damien-VS commented
Non, il n' y en a pas. c'est un événement interne ouvert aux speakers externes.
Les infos de l'événement sont dans l'en-tête du CFP

2023-04-17 07:20 UTC, scraly requested changes

2023-04-17 07:20 UTC, scraly commented on README.md
> +* 20-22: [Adeo DevSummit](https://forms.gle/YPcjupChvqQif85B9) - Lille (France) <a href="https://forms.gle/YPcjupChvqQif85B9"><img alt="CFP adeo DevSummit 2023" src="https://img.shields.io/static/v1?
```suggestion
* 20-22: [Adeo DevSummit](https://forms.gle/YPcjupChvqQif85B9) - Lille (France) <a href="https://forms.gle/YPcjupChvqQif85B9"><img alt="CFP adeo DevSummit 2023" src="https://img.shields.io/static/v1?label=CFP&message=until%2019-May-2023&color=green"></a> <img alt="Internal event by Adeo open for external speakers" src="https://img.shields.io/static/v1?label=Internal&message=Event&color=purple"/>
```

2023-04-17 08:05 UTC, Damien-VS commented
> Bonjour,
> 
> Le fait que l'événement soit interne devrait être très spécifiquement précisé dans le CFP. Cela peut fortement jouer sur l'acceptation d'un employeur à prendre en charge les frais de déplacement/hôtellerie pour un speaker.

Ajouté dans le CFP
ainsi qu'une note sur le fait que les frais peuvent être supportés par adeo sur demande.

2023-04-17 08:19 UTC, scraly commented
thanks :)

2023-04-17 08:19 UTC, merged