Adding TechRocks Summit 7-8 dec
scraly/developers-conferences-agenda pull request #456
Opened 2023-04-27 09:06 UTC by pensarguet

Adding TechRocks Summit 7-8 dec

2023-04-27 20:57 UTC, scraly requested changes
thanks
just a suggestion ;)

2023-04-27 20:57 UTC, scraly commented on README.md
> +* 7-8: [TechRocks Summit](https://events.tech.rocks/summit-2023/fr/registration/ticketing) - Comet Meetings - Bourse 75002 Paris (France)
```suggestion
* 7-8: [TechRocks Summit](https://events.tech.rocks/summit-2023/fr/) - Paris (France)
```

2023-04-28 08:15 UTC, pensarguet commented on README.md
> +* 7-8: [TechRocks Summit](https://events.tech.rocks/summit-2023/fr/registration/ticketing) - Comet Meetings - Bourse 75002 Paris (France)
ok ;)

2023-04-28 08:19 UTC, merged

2023-04-28 08:19 UTC, scraly commented
thanks :)