Added KCD Texas
scraly/developers-conferences-agenda pull request #520
Opened 2023-06-07 16:24 UTC by jjasghar

Added KCD Texas 2023

2023-06-07 18:49 UTC, scraly requested changes

2023-06-07 18:49 UTC, scraly commented on README.md
> +* 6: [KCD Texas](https://texaskcd.com) - Dallas/Irving, Texas <a href="https://kcd.smapply.io/prog/kcd-texas-2023/"><img alt="KCD Texas 2023" src="https://img.shields.io/static/v1?label=CFP&message=u
```suggestion
* 6: [KCD Texas](https://texaskcd.com) - Dallas/Irving, Texas (USA) <a href="https://kcd.smapply.io/prog/kcd-texas-2023/"><img alt="KCD Texas 2023" src="https://img.shields.io/static/v1?label=CFP&message=until%2030-August-2023&color=green"></a>
```

2023-06-07 20:51 UTC, jjasghar commented
Updated :)

2023-06-08 05:20 UTC, merged

2023-06-08 05:20 UTC, scraly commented
Thanks