fixed
scraly/developers-conferences-agenda pull request #663
Opened 2023-10-16 11:46 UTC by harshsbhandari

Fixed issue #645.

2023-10-16 12:22 UTC, scraly requested changes

2023-10-16 12:22 UTC, scraly commented on page/src/styles/YearSelector.css
> +
Please add also:

```
.arrowButton{
  cursor: pointer;
}
```

2023-10-16 12:23 UTC, scraly commented
Please add the pointer cursor from all the arrow buttons.

Also fo these ones:
<img width="371" alt="image" src="https://github.com/scraly/developers-conferences-agenda/assets/2543381/57b8ab90-8870-4236-9cc8-d28a56ac8ab5">

2023-10-17 15:28 UTC, harshsbhandari commented
> Please add the pointer cursor from all the arrow buttons.
> 
> Also for these ones: <img alt="image" width="371" src="https://user-images.githubusercontent.com/2543381/275502077-57b8ab90-8870-4236-9cc8-d28a56ac8ab5.png">

Done ma'am, sorry I missed it.

2023-10-17 16:26 UTC, scraly commented
It is still not working for eventDateDisplay's arrow buttons ☺️.

2023-10-18 15:00 UTC, harshsbhandari commented
> It is still not working for eventDateDisplay's arrow buttons ☺️.

Hi ma'am, made some changes, please let me know if that works

2023-10-18 20:50 UTC, scraly commented
Still not working.

here more information about these arrows buttons:
<img width="1430" alt="image" src="https://github.com/scraly/developers-conferences-agenda/assets/2543381/714c2183-4176-46cb-b350-d9f44fa703b4">

2023-10-19 04:51 UTC, harshsbhandari commented
> Still not working.
> 
> here more information about these arrows buttons: <img alt="image" width="1430" src="https://user-images.githubusercontent.com/2543381/276397608-714c2183-4176-46cb-b350-d9f44fa703b4.png">

does it works now, made changes

2023-10-20 21:31 UTC, scraly commented
No it does not work.

To fix it, just edit the `EventDisplay.css` file:

```
.lucide-arrow-right-circle {
  cursor: pointer;
}

.lucide-arrow-left-circle {
  cursor: pointer;
}
```

2023-10-21 05:26 UTC, harshsbhandari commented
> No it does not work.
> 
> To fix it, just edit the `EventDisplay.css` file:
> 
> ```
> .lucide-arrow-right-circle {
>   cursor: pointer;
> }
> 
> .lucide-arrow-left-circle {
>   cursor: pointer;
> }
> ```

Made changes as instructed.

2023-10-21 09:53 UTC, scraly commented
So with my fiw now you know in which css class you need to add effects ;-)

2023-10-21 15:07 UTC, harshsbhandari commented
> So with my fiw now you know in which css class you need to add effects ;-)

yes, does it works fine now?

2023-10-21 16:48 UTC, scraly requested changes
yes the fix I show you is to have the pointer cursor.
So in order to add effects, you have to add this:

```
.lucide-arrow-right-circle :hover{
  cursor: pointer;
  transition: transform 0.5s;
  transform: scale(1.07);
  -webkit-transform: scale(1.07);
  -moz-transform: scale(1.07);
  -ms-transform: scale(1.07);
  -o-transform: scale(1.07);
  -webkit-transition: transform 0.5s;
  -moz-transition: transform 0.5s;
  -ms-transition: transform 0.5s;
  -o-transition: transform 0.5s;
}

.lucide-arrow-left-circle :hover{
  cursor: pointer;
  transition: transform 0.5s;
  transform: scale(1.07);
  -webkit-transform: scale(1.07);
  -moz-transform: scale(1.07);
  -ms-transform: scale(1.07);
  -o-transform: scale(1.07);
  -webkit-transition: transform 0.5s;
  -moz-transition: transform 0.5s;
  -ms-transition: transform 0.5s;
  -o-transition: transform 0.5s;
}
```

You have also to remove "fix" you added but that did not work.

Thanks

2023-10-22 06:36 UTC, closed without merging

2023-10-22 10:22 UTC, scraly commented
@harshsbhandari  why have you closed this PR? :)

2023-10-22 10:37 UTC, scraly commented
I created a new PRs, now the buttons have effects, thanks! :)