add kubecon China in Hong Kong
scraly/developers-conferences-agenda pull request #861
Opened 2024-02-06 02:30 UTC by pacoxu

CFP and official website are not ready yet
CFP is probably closed in late April or May.

2024-02-07 09:34 UTC, scraly commented
Whent he website will be live can you update the PR and then I will merge it? :)

2024-02-07 09:46 UTC, pacoxu commented
> Whent he website will be live can you update the PR and then I will merge it? :)

China Spring Festival is this week and I think most Chinese will have a 1 or 2 week holidays this week and the next. 

I think the website will be ready late Feb. I will help update the link and CFP link later.

2024-03-12 17:36 UTC, scraly requested changes

2024-03-12 17:36 UTC, scraly commented on README.md
> +* 21-22: [KubeCon + CloudNativeCon + Open Source Summit + AI dev China 2024]([https://events.linuxfoundation.org/?_sft_lfevent-category=kubecon-cloudnativecon-cncf-events](https://events.linuxfoundat
```suggestion
* 21-22: [KubeCon + CloudNativeCon + Open Source Summit + AI dev China 2024](https://events.linuxfoundation.org/kubecon-cloudnativecon-open-source-summit-ai-dev-china/) - Hong Kong (China)

2024-03-12 17:40 UTC, merged