Adding a color validator and updated the cfp colors
scraly/developers-conferences-agenda pull request #905
Opened 2024-03-18 11:59 UTC by jespino

2024-03-18 20:45 UTC, scraly requested changes
Thanks, it's a good idea :) 

Please edit `run.sh` script also with a new line at the end:

```
node validateCFPColor.js
```

And change `validateCfpColor.js` to `validateCFPColor.js`

2024-03-18 20:45 UTC, scraly commented on tools/validateCfpColor.js
> +        console.log("Invalid cfp green color: " + new Date(event.date[0]).toISOString() + " " + event.name);
```suggestion
        console.log("Invalid CFP green color: " + new Date(event.date[0]).toISOString() + " " + event.name);
```

2024-03-18 20:45 UTC, scraly commented on tools/validateCfpColor.js
> +        console.log("Invalid cfp red color: " + new Date(event.date[0]).toISOString() + " " + event.name);
```suggestion
        console.log("Invalid CFP red color: " + new Date(event.date[0]).toISOString() + " " + event.name);
```

2024-03-19 09:51 UTC, jespino commented
Done

2024-03-22 20:33 UTC, merged

2024-03-22 20:33 UTC, scraly commented
gracias! :)